# Generated by Django 3.0.6 on 2020-06-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('l', 'link')], default='p', max_length=1, null=True),
        ),
    ]
