# Generated by Django 3.0.6 on 2020-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_goods_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'get_latest_by': 'created', 'managed': True, 'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='goods',
            name='url',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
